window.SITE_CONTENT = {
  "hero_h1": "Shaping a human-centered future.",
  "hero_sub": "Technology is changing faster than society can adapt. Access Insights is building durable research innovation infrastructure to help people, funders, and organizations focus on the highest-value human needs, validate better solutions, and move trusted ideas toward scale.",
  "work_eyebrow": "Pipeline",
  "work_h2": "Durable infrastructure for moving ideas from need to scale.",
  "work_intro": "Access Insights brings discovery, research, partnerships, and implementation pathways into one connected system that grows stronger with every project.",
  "work_s1_tag": "Discover",
  "work_s1_h": "Identify the highest-value opportunities",
  "work_s1_p": "Surface lived experience, barriers, trust signals, and patterns that reveal where effort can create the greatest value.",
  "work_s2_tag": "Validate",
  "work_s2_h": "Build evidence people can trust",
  "work_s2_p": "Select the research approach that fits the question, from focused studies to deeper Living Lab engagements.",
  "work_s3_tag": "Scale",
  "work_s3_h": "Connect innovation with implementation",
  "work_s3_p": "Link validated work to the partners, funders, and organizations positioned to carry it forward.",
  "work_note": "Living Labs are our deepest research capability: a way to evaluate ideas alongside the people, environments, and organizations they are designed to serve.",
  "why_eyebrow": "Strategic rationale",
  "why_h2": "Better decisions create better innovation.",
  "why_p1": "Technology is advancing faster than our ability to understand how people will use it, trust it, and adapt with it. Access Insights helps organizations focus on high-value opportunities before development begins, build trustworthy evidence, and move successful ideas toward lasting adoption.",
  "why_c1_n": "Before development",
  "why_c1_h": "Focus effort where value is highest",
  "why_c1_p": "Use disability, aging, and human variability as powerful sources of insight into barriers, adaptation, and trust.",
  "why_c2_n": "During development",
  "why_c2_h": "Build evidence people can trust",
  "why_c2_p": "Test whether ideas are useful, usable, accessible, trusted, and ready for everyday conditions.",
  "why_c3_n": "Toward implementation",
  "why_c3_h": "Connect validated work to scale",
  "why_c3_p": "Help promising work reach the people and organizations that can turn evidence into lasting benefit.",
  "trust_eyebrow": "Trust & commitments",
  "trust_h2": "Built around trust, participation, and impact.",
  "trust_intro": "Innovation depends on trust. We design research programs that respect participants, protect information, and create value for everyone involved.",
  "trust_pr1_h": "Voluntary",
  "trust_pr1_p": "Participation is always voluntary, with consent at every step.",
  "trust_pr2_h": "Private",
  "trust_pr2_p": "Consent and privacy are top priorities, with retention and deletion built in.",
  "trust_pr3_h": "Accessible",
  "trust_pr3_p": "Accessibility is built into the research experience, not bolted on.",
  "trust_pr4_h": "Accountable",
  "trust_pr4_p": "Clear governance and auditability, so contributions and outcomes are understood.",
  "trust_nosell": "We do not sell participant data.",
  "impact_eyebrow": "Collective impact",
  "impact_h2": "Built by people who have spent decades moving ideas into practice.",
  "impact_intro": "Access Insights brings together leaders in research, accessibility, engineering, design, policy, and innovation who have shaped technologies, standards, and public policy that improve people&rsquo;s lives.",
  "impact_story": "We are now building the next chapter: durable infrastructure that helps society make better decisions about what to create, how to evaluate it, and how to ensure it serves people.",
  "stat1_b": "60+",
  "stat1_s": "patents across acoustics, AR, and AI",
  "stat2_b": "1,200+",
  "stat2_s": "lectures, from the White House to the UN",
  "stat3_b": "167+",
  "stat3_s": "peer-reviewed publications",
  "stat4_b": "200+ yrs",
  "stat4_s": "combined work shaping policy & standards",
  "p1_nm": "Darryl Adams",
  "p1_role": "Founder",
  "p1_p": "AI and accessibility strategist focused on inclusive innovation and real-world impact.",
  "p2_nm": "Lex Frieden",
  "p2_role": "Senior Advisor",
  "p2_p": "Chief architect of the ADA and a founder of the independent living movement; five decades shaping U.S. and international disability policy.",
  "p3_nm": "Richard Beckwith, PhD",
  "p3_role": "Research Fellow",
  "p3_p": "Long career doing research in support of design across disability, education, and aging. UX, AI, especially NLP, and sensing.",
  "p4_nm": "Marco Beltman, PhD",
  "p4_role": "Research Fellow, Sensory Technology",
  "p4_p": "Principal engineer with a PhD in acoustics, 39 patents, and a volunteer raft guide opening rivers to people of all abilities.",
  "p5_nm": "Becky Chierichetti",
  "p5_role": "Principal Design Research Lead",
  "p5_p": "UX researcher exploring AI, mixed reality, and accessibility at the boundary of physical and digital worlds.",
  "p6_nm": "Pete Denman",
  "p6_role": "Principal Design / Interaction",
  "p6_p": "Designed Stephen Hawking's communication system; over 30 years in visual and interaction design, bringing the perspective of a wheelchair user to every project.",
  "p7_nm": "Susan Faulkner",
  "p7_role": "Research Director",
  "p7_p": "User experience researcher and leader with over 30 years delivering high-impact results focused on accessibility.",
  "proto_eyebrow": "Proto-Lab",
  "proto_h2": "Exploring what comes next.",
  "proto_intro": "Proto-Lab explores ideas that emerge from patterns we see across research, technology, and community partnerships. It is where we invest our own curiosity into tools and concepts intended to create shared benefit.",
  "proto_p2": "Over time, Proto-Lab may grow into a physical innovation space for rapid prototyping, accessible fabrication, research, and community collaboration.",
  "proj1_t": "Open Source",
  "proj1_h": "UnisonOS",
  "proj1_tl": "An operating surface for intention-centered computing.",
  "proj1_p": "Treats a person's intention as the primary interface, with voice, text, vision, touch, Braille, sign, and BCI as first-class channels. Accessibility is the model, not a mode.",
  "proj2_t": "Presence",
  "proj2_h": "Virtual Lex",
  "proj2_tl": "Establishing presence when you cannot be present.",
  "proj2_p": "Built so Lex Frieden could attend the 35th-anniversary ADA celebrations with a real sense of being in the room: binaural audio, spatial orientation, and an animated avatar that engages the room directly.",
  "mom_eyebrow": "Building Momentum",
  "mom_h2": "Building the foundation now.",
  "mom_intro": "Access Insights is completing its first Living Lab pilot, advancing the goalball project, growing the UX research participant community, building funder and partner relationships, and developing the digital infrastructure that supports research operations over time.",
  "fund_eyebrow": "Funding and partnership",
  "fund_h2": "Build the future with us.",
  "fund_p": "Foundations and mission-aligned organizations help make this work possible by investing in durable research infrastructure, trusted participant engagement, community partnerships, Living Labs, and open innovation that creates shared benefit. Start a conversation with us about where your mission and this work can meet.",
  "part_eyebrow": "Join the Research Community",
  "part_h2": "Help shape what&rsquo;s next.",
  "part_p": "Sign up or sign in to the Access Insights research platform to participate in studies, product evaluations, interviews, surveys, Living Labs, and future research opportunities. Your experience can help guide higher-value innovation.",
  "part_signin": "Sign in",
  "part_join": "Join the Research Community"
};
