window.SITE_CONTENT = {
  "hero_h1": "Shaping a human-centered future.",
  "hero_sub": "Technology is changing faster than society can adapt. Access Insights is building research innovation infrastructure that helps turn high-value human needs into trusted solutions. We identify the highest-value opportunities, validate them through the right research approaches, and connect successful ideas with partners who can bring them to scale. Together, we are shaping a human-centered future.",
  "work_eyebrow": "Pipeline",
  "work_h2": "Research innovation infrastructure for moving ideas from need to scale.",
  "work_intro": "Access Insights helps partners discover the highest-value opportunities, validate them through the right research approach, and connect proven ideas with the people and organizations positioned to carry them forward.",
  "work_s1_tag": "Discover",
  "work_s1_h": "Identify the highest-value opportunities",
  "work_s1_p": "Surface lived-context patterns, barriers, trust signals, and opportunity areas so effort starts in the highest-value places.",
  "work_s2_tag": "Validate",
  "work_s2_h": "Choose the right research approach",
  "work_s2_p": "Use interviews, surveys, contextual inquiry, usability studies, co-design, field research, and Living Labs to build evidence people can trust.",
  "work_s3_tag": "Scale",
  "work_s3_h": "Connect innovation with implementation",
  "work_s3_p": "Link validated work to funders, nonprofits, industry teams, and research organizations with the reach and capacity to implement it.",
  "work_note": "Living Labs are our deepest research environment, especially valuable when projects require longitudinal observation, everyday context, multiple stakeholders, iterative deployment, and organizational participation. Not every project needs a Living Lab, but the capability is there when depth matters.",
  "cap_eyebrow": "Research capabilities",
  "cap_h2": "Research where it creates the greatest value.",
  "cap_intro": "We select methods around the decision that needs to be made, the people affected, and the evidence required to move responsibly from concept to implementation.",
  "cap_1": "Participant community research",
  "cap_2": "Interviews and contextual inquiry",
  "cap_3": "Surveys and quantitative studies",
  "cap_4": "Accessibility and usability evaluation",
  "cap_5": "Co-design workshops",
  "cap_6": "Living Labs",
  "cap_7": "Longitudinal field studies",
  "cap_8": "AI and emerging technology evaluation",
  "why_eyebrow": "Strategic rationale",
  "why_h2": "Better decisions create better innovation.",
  "why_p1": "Technology has never advanced faster, and understanding how people live, adapt, and build trust has never been more important. The highest-value human needs are not always obvious at the beginning of a project, especially when new technology changes what is possible.",
  "why_p2": "Access Insights helps organizations focus on the highest-value opportunities before development begins, generate trustworthy evidence throughout the process, and connect validated work with the people and organizations positioned to carry it forward.",
  "why_c1_n": "Before development",
  "why_c1_h": "Focus effort where value is highest",
  "why_c1_p": "We use disability, aging, and the full range of human variability as powerful sources of insight into needs, barriers, adaptation, and trust.",
  "why_c2_n": "During development",
  "why_c2_h": "Build evidence people can trust",
  "why_c2_p": "Our research programs test whether ideas are useful, usable, accessible, trusted, and ready for real-world conditions.",
  "why_c3_n": "Toward implementation",
  "why_c3_h": "Connect validated work to scale",
  "why_c3_p": "We help promising work reach funders, partners, communities, and implementers who can turn evidence into lasting benefit.",
  "trust_eyebrow": "Trust & commitments",
  "trust_h2": "Built around trust, participation, and impact.",
  "trust_intro": "Innovation depends on trust. We build research programs that respect participants, protect their information, and create value that benefits everyone involved.",
  "trust_pr1_h": "Voluntary",
  "trust_pr1_p": "Participation is always voluntary, with consent at every step.",
  "trust_pr2_h": "Private",
  "trust_pr2_p": "Consent and privacy are top priorities, with retention and deletion built in.",
  "trust_pr3_h": "Accessible",
  "trust_pr3_p": "Accessibility is built into the research experience, not bolted on.",
  "trust_pr4_h": "Accountable",
  "trust_pr4_p": "Clear governance and auditability, so contributions and outcomes are understood.",
  "trust_nosell": "We do not sell participant data.",
  "impact_eyebrow": "Collective impact",
  "impact_h2": "Built by people who have spent decades moving ideas into practice.",
  "impact_intro": "Access Insights brings together leaders in research, accessibility, engineering, design, policy, and innovation who have spent their careers shaping technologies, standards, and public policy that improve people's lives.",
  "impact_story": "Many of us first worked together years ago on projects grounded in disability, aging, and inclusive technology. Over time, our careers moved through different organizations and disciplines, but the same commitment kept bringing us back together: use deep human insight to help promising ideas become practical, trusted solutions.",
  "stat1_b": "60+",
  "stat1_s": "patents across acoustics, AR, and AI",
  "stat2_b": "1,200+",
  "stat2_s": "lectures, from the White House to the UN",
  "stat3_b": "167+",
  "stat3_s": "peer-reviewed publications",
  "stat4_b": "200+ yrs",
  "stat4_s": "combined work shaping policy & standards",
  "p1_nm": "Darryl Adams",
  "p1_role": "Founder",
  "p1_p": "AI and accessibility strategist focused on inclusive innovation and real-world impact.",
  "p2_nm": "Lex Frieden",
  "p2_role": "Senior Advisor",
  "p2_p": "Chief architect of the ADA and a founder of the independent living movement; five decades shaping U.S. and international disability policy.",
  "p3_nm": "Richard Beckwith, PhD",
  "p3_role": "Research Fellow",
  "p3_p": "Long career doing research in support of design across disability, education, and aging. UX, AI, especially NLP, and sensing.",
  "p4_nm": "Marco Beltman, PhD",
  "p4_role": "Research Fellow, Sensory Technology",
  "p4_p": "Principal engineer with a PhD in acoustics, 39 patents, and a volunteer raft guide opening rivers to people of all abilities.",
  "p5_nm": "Becky Chierichetti",
  "p5_role": "Principal Design Research Lead",
  "p5_p": "UX researcher exploring AI, mixed reality, and accessibility at the boundary of physical and digital worlds.",
  "p6_nm": "Pete Denman",
  "p6_role": "Principal Design / Interaction",
  "p6_p": "Designed Stephen Hawking's communication system; over 30 years in visual and interaction design, bringing the perspective of a wheelchair user to every project.",
  "p7_nm": "Susan Faulkner",
  "p7_role": "Research Director",
  "p7_p": "User experience researcher and leader with over 30 years delivering high-impact results focused on accessibility.",
  "proto_eyebrow": "Proto-Lab",
  "proto_h2": "Exploring what comes next.",
  "proto_intro": "Most Access Insights work begins with research and collaboration. Proto-Lab is our exploration and giving-back engine, where we investigate ideas that emerge from patterns seen across projects, communities, and technologies.",
  "proto_p2": "Proto-Lab projects are intended to create shared benefit. Some may become open source software, reference designs, research publications, public methods, standards contributions, or future nonprofit initiatives. Over time, Proto-Lab may also evolve into a physical innovation space with prototyping equipment, accessible fabrication, research space, and tools that help promising ideas become real faster.",
  "proj1_t": "Open Source",
  "proj1_h": "UnisonOS",
  "proj1_tl": "An operating surface for intention-centered computing.",
  "proj1_p": "Treats a person's intention as the primary interface, with voice, text, vision, touch, Braille, sign, and BCI as first-class channels. Accessibility is the model, not a mode.",
  "proj2_t": "Presence",
  "proj2_h": "Virtual Lex",
  "proj2_tl": "Establishing presence when you cannot be present.",
  "proj2_p": "Built so Lex Frieden could attend the 35th-anniversary ADA celebrations with a real sense of being in the room: binaural audio, spatial orientation, and an animated avatar that engages the room directly.",
  "mom_eyebrow": "Building Momentum",
  "mom_h2": "Access Insights is actively building the foundation for a new model of human-centered innovation.",
  "mom_intro": "Our current priorities combine field research, community development, partnership building, and digital infrastructure so the model can grow responsibly.",
  "mom_1": "Completing the first Living Lab pilot with an independent living community in Portland.",
  "mom_2": "Advancing the goalball project as an example of collaborative assistive technology innovation.",
  "mom_3": "Expanding the UX research participant community.",
  "mom_4": "Building relationships with funders, nonprofits, industry partners, and research organizations.",
  "mom_5": "Building the digital infrastructure that supports the participant community, partner network, and research operations.",
  "fund_eyebrow": "Funding and partnership",
  "fund_h2": "Build the future with us.",
  "fund_p": "Foundations and mission-aligned organizations help make this work possible by investing in research infrastructure, community partnerships, Living Labs, participant engagement, and open innovation that creates shared benefit. Start a conversation with us about where your mission and this work can meet.",
  "part_eyebrow": "Join the Research Community",
  "part_h2": "Help shape what's next.",
  "part_p": "Join the Access Insights research community to participate in interviews, product evaluations, surveys, usability studies, Living Labs, and future research opportunities. Whether you live with a disability, are an older adult, are a caregiver, or simply want to help shape better technology, your perspective can help guide higher-value innovation.",
  "part_signin": "Sign in",
  "part_join": "Join the Research Community"
};
