window.SITE_CONTENT = {
  "hero_h1": "Shaping a human-centered future.",
  "hero_sub": "Access Insights helps turn real human needs into real solutions. With your support, we find the needs that matter most, test whether solutions actually work, and move good ideas from insight to impact faster.",
  "work_eyebrow": "Pipeline",
  "work_h2": "A pipeline for turning unmet needs into scaled impact.",
  "work_intro": "We find the strongest needs, test them in our Living Labs, and connect partners who can scale the result.",
  "work_s1_tag": "Start",
  "work_s1_h": "Find the needs",
  "work_s1_p": "Capture and score barriers, lived-context patterns, and opportunity signals, bringing forward the unmet needs most likely to matter.",
  "work_s2_tag": "Our Living Labs",
  "work_s2_h": "Test where people live",
  "work_s2_p": "Collaborations with independent and assisted living communities, where resident, staff, and leadership voices are heard together.",
  "work_s3_tag": "Scale",
  "work_s3_h": "Activate partners",
  "work_s3_p": "Connect validated solutions to partners with the reach, sites, services, and capacity to get them to the people who need them.",
  "work_note": "Living Labs are the distinctive middle of our pipeline: the place where promising ideas meet real lives before anyone bets on scaling them.",
  "why_eyebrow": "Pipeline: What success looks like",
  "why_h2": "Access Insights shows up early and stays late",
  "why_p1": "Often innovation pipelines fail because they don't start with the right information. It is common for teams to build around a need they assume is real, without enough evidence about how people actually live. At the conclusion of a project, even strong prototypes stall in the implementation.",
  "why_p2": "We work with teams at critical points to foster success, helping prioritize the right needs at the start and lining up the partners who can deploy and sustain solutions through iterations and into the deployment process.",
  "why_c1_n": "The need: the beginning",
  "why_c1_h": "Find what matters most",
  "why_c1_p": "We surface and score real, lived barriers, focused on disability, aging, and the full range of human variability, so effort goes where it counts.",
  "why_c2_n": "The method",
  "why_c2_h": "Prove what actually works",
  "why_c2_p": "Platform-managed research and Living Labs test whether a solution is useful, usable, trusted, accessible, and ready for the real world.",
  "why_c3_n": "The return: to finish",
  "why_c3_h": "Reach real communities",
  "why_c3_p": "We connect validated work to the partners who can deploy and sustain it, turning your investment into solutions people use.",
  "trust_eyebrow": "Trust & commitments",
  "trust_h2": "Built around trust, participation, and impact.",
  "trust_intro": "We create value through trusted, ethical engagement, aggregate or de-identified insight, and rigorous research operations. This is work funders can stand behind.",
  "trust_pr1_h": "Voluntary",
  "trust_pr1_p": "Participation is always voluntary, with consent at every step.",
  "trust_pr2_h": "Private",
  "trust_pr2_p": "Consent and privacy are top priorities, with retention and deletion built in.",
  "trust_pr3_h": "Accessible",
  "trust_pr3_p": "Accessibility is built into the research experience, not bolted on.",
  "trust_pr4_h": "Accountable",
  "trust_pr4_p": "Clear governance and auditability, so contributions and outcomes are understood.",
  "trust_nosell": "We do not sell participant data.",
  "impact_eyebrow": "Collective impact",
  "impact_h2": "7 friends 1 altruistic goal. Contribute to the disability community!",
  "impact_intro": "Access Insights brings together researchers, designers, technologists, and disability rights pioneers, including the chief architect of the ADA, whose work shaped the laws millions rely on and the tools billions use.",
  "impact_story": "For years we worked side by side on projects much like the ones we hope you'll bring us. Working together is simply more fun and more impactful. As our careers have taken us in different directions, we've gravitated back together to work on projects that make a difference. Most of us live with a disability, and all of us lead with empathy. For us, that is where good work starts.",
  "stat1_b": "60+",
  "stat1_s": "patents across acoustics, AR, and AI",
  "stat2_b": "1,200+",
  "stat2_s": "lectures, from the White House to the UN",
  "stat3_b": "167+",
  "stat3_s": "peer-reviewed publications",
  "stat4_b": "200+ yrs",
  "stat4_s": "combined work shaping policy & standards",
  "p1_nm": "Darryl Adams",
  "p1_role": "Founder",
  "p1_p": "AI and accessibility strategist focused on inclusive innovation and real-world impact.",
  "p2_nm": "Lex Frieden",
  "p2_role": "Senior Advisor",
  "p2_p": "Chief architect of the ADA and a founder of the independent living movement; five decades shaping U.S. and international disability policy.",
  "p3_nm": "Richard Beckwith, PhD",
  "p3_role": "Research Fellow",
  "p3_p": "Long career doing research in support of design across disability, education, and aging. UX, AI, especially NLP, and sensing.",
  "p4_nm": "Marco Beltman, PhD",
  "p4_role": "Research Fellow, Sensory Technology",
  "p4_p": "Principal engineer with a PhD in acoustics, 39 patents, and a volunteer raft guide opening rivers to people of all abilities.",
  "p5_nm": "Becky Chierichetti",
  "p5_role": "Principal Design Research Lead",
  "p5_p": "UX researcher exploring AI, mixed reality, and accessibility at the boundary of physical and digital worlds.",
  "p6_nm": "Pete Denman",
  "p6_role": "Principal Design / Interaction",
  "p6_p": "Designed Stephen Hawking's communication system; over 30 years in visual and interaction design, bringing the perspective of a wheelchair user to every project.",
  "p7_nm": "Susan Faulkner",
  "p7_role": "Research Director",
  "p7_p": "User experience researcher and leader with over 30 years delivering high-impact results focused on accessibility.",
  "proto_eyebrow": "Proto-Lab",
  "proto_h2": "Builds from the needs research reveals.",
  "proto_intro": "A space for tools, projects, and resources worth finding: ones that address real human needs but sit outside our current pipeline work.",
  "proj1_t": "Open Source",
  "proj1_h": "UnisonOS",
  "proj1_tl": "An operating surface for intention-centered computing.",
  "proj1_p": "Treats a person's intention as the primary interface, with voice, text, vision, touch, Braille, sign, and BCI as first-class channels. Accessibility is the model, not a mode.",
  "proj2_t": "Presence",
  "proj2_h": "Virtual Lex",
  "proj2_tl": "Establishing presence when you cannot be present.",
  "proj2_p": "Built so Lex Frieden could attend the 35th-anniversary ADA celebrations with a real sense of being in the room: binaural audio, spatial orientation, and an animated avatar that engages the room directly.",
  "fund_eyebrow": "Fund this work",
  "fund_h2": "Start a conversation about funding and strategic collaboration.",
  "fund_p": "Foundations and mission-aligned funders make this pipeline possible. Let's talk about grants, strategic giving, and the impact your support creates.",
  "part_eyebrow": "For participants",
  "part_h2": "Already part of the research community?",
  "part_p": "Log in to access your studies, preferences, and support paths, or join the User Experience Program if you're new. Everyone is welcome."
};
